language: python

sudo: required

python: "2.7"

matrix:
  fast_finish: true
  include:
    - dist: trusty
      env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-trunk-daily"
    - dist: trusty
      env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.6-daily"
    - dist: trusty
      env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.5-daily"
    - dist: trusty
      env: COQ_VERSION="8.6"      COQ_PACKAGE="coq-8.6"                        PPA="ppa:jgross-h/many-coq-versions"
    - dist: trusty
      env: COQ_VERSION="8.5pl3"  COQ_PACKAGE="coq-8.5pl3 libcoq-ocaml-8.5pl3" PPA="ppa:jgross-h/many-coq-versions"
    - dist: precise
      env: COQ_VERSION="8.4pl6"  COQ_PACKAGE="coq-8.4pl6 libcoq-ocaml-8.4pl6" PPA="ppa:jgross-h/many-coq-versions-ocaml-3"
  allow_failures:
    - env: COQ_VERSION="v8.5"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.5-daily"
    - env: COQ_VERSION="v8.6"     COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-8.6-daily"
    - env: COQ_VERSION="trunk"    COQ_PACKAGE="coq"                            PPA="ppa:jgross-h/coq-trunk-daily"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

script: make has-all-tests && make check CAT_ALL_LOGS=1
