name: CI (check-all)

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
    - name: echo workflow params
      run: |
        echo 'artifacts_url  : ${{ github.event.workflow_run.artifacts_url   }}'
        echo 'check_suite_id : ${{ github.event.workflow_run.check_suite_id  }}'
        echo 'check_suite_url: ${{ github.event.workflow_run.check_suite_url }}'
        echo 'conclusion     : ${{ github.event.workflow_run.conclusion      }}'
        echo 'head_branch    : ${{ github.event.workflow_run.head_branch     }}'
        echo 'head_sha       : ${{ github.event.workflow_run.head_sha        }}'
    - run: echo 'The triggering workflow passed'
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
    - run: echo 'The triggering workflow failed' && false
      if: ${{ github.event.workflow_run.conclusion != 'success' }}
